In [1]:
## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time
import random

In [3]:
## Webscrapping Request Generation check

In [4]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9"
}

response=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers=headers).text

In [5]:
## Intializing variable

In [6]:
soup=BeautifulSoup(response,'lxml')

In [7]:
## Extracting name of company from page 1

In [8]:
for i in soup.find_all('h2')[1:]:
    print(i.text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [9]:
## Extracting rating of company from page 1

In [10]:
for i in soup.find_all('div',class_='rating_text'):
    print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
3.9
3.3
3.6
3.9
3.6
4.4
3.5
3.9
3.9
4.6
3.6
3.9

In [11]:
## Extracting rating of company from page 1

In [12]:
for i in soup.find_all('span',class_='companyCardWrapper__companyRatingCount'):
    print(i.text.strip().replace('(','').replace(')',''))

1.2L
75.3k
66.5k
62.7k
54.8k
53.9k
50k
47.1k
46.8k
44.3k
43.5k
39.7k
34.2k
34.1k
33k
32.4k
27.8k
27.5k
27k
26.3k

In [13]:
## Extracting types of company from page 1

In [14]:
j=[]
for i in soup.find_all('span',class_='companyCardWrapper__interLinking'):
    j.append(i.text.strip().split('|')[0])
j

['IT Services & Consulting ',
 'IT Services & Consulting ',
 'IT Services & Consulting ',
 'IT Services & Consulting ',
 'IT Services & Consulting ',
 'Banking ',
 'IT Services & Consulting ',
 'IT Services & Consulting ',
 'Banking ',
 'IT Services & Consulting ',
 'Analytics & KPO ',
 'BPO ',
 'Banking ',
 'Telecom ',
 'BPO ',
 'Internet ',
 'Retail ',
 'BPO ',
 'IT Services & Consulting ',
 'NBFC ']

In [15]:
## final code: Extracting name, rating, count of votes,types of comapny, hq, salary, jobs count, benefits 
## from all available webpages

In [4]:
final=pd.DataFrame()
dfs=[]
session=requests.Session()
for a in range(1,500):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9"
    }
    
    response=session.get(f'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={a}',headers=headers,timeout=10)
    print('page',a,':',response.status_code)
    if response.status_code==403:
        print('Blocked by Ambition Box')
        break
    if response.status_code!=200:
        continue
    soup=BeautifulSoup(response.text,'lxml')
    
    name=[]
    rating=[]
    count=[]
    info=[]
    types=[]
    hq=[]
    salary=[]
    interview=[]
    jobs=[]
    benefits=[]
    company=soup.find_all('div',class_='companyCardWrapper')
    print('Page:',a,'-',len(company),'companies')
    if not company:
            break
    for i in company:
        try:
            name.append(i.find('h2').text.strip())
        except:
            name.append(np.nan)
        try:
            rating.append(i.find('div',class_='rating_text').text.strip())
        except:
            rating.append(np.nan)
        try:
            count.append(i.find('span',class_='companyCardWrapper__companyRatingCount').text.strip().replace('(','').replace(')',''))
        except:
            count.append(np.nan)
        
        try:
            j=i.find('span',class_='companyCardWrapper__interLinking').text.strip()
        except:
            j=''
        info.append(j)
        
        if '|' in j:
            x=j.split('|') 
            k=x[0].strip() 
            l=x[1].strip()  
            m=l.split('+')[0].strip()
        else:
            x=j.split('+')
            k=np.nan
            l=np.nan
            m=x[0].strip() if j else np.nan
            
        try:
            types.append(k)
        except:
            types.append(np.nan)
        try:
            hq.append(m)
        except:
            hq.append(np.nan)
        action=i.find_all('span',class_='companyCardWrapper__ActionCount')
        try:
            salary.append(action[1].text.strip())
        except:
            salary.append(np.nan)
       
        try:
            interview.append(action[2].text.strip())
        except:
            interview.append(np.nan)
        try:
            jobs.append(action[3].text.strip())
        except:
            jobs.append(np.nan)
        try:
            benefits.append(action[4].text.strip())
        except:
            benefits.append(np.nan)

    temp_df=pd.DataFrame({
        'name':name,
        'ratings':rating,
        'count_of_rating':count,
        'company_types':types,
        'hq':hq,
        'salary':salary,
        'interview_counts':interview,
        'jobs':jobs,
        'benefits':benefits
    })
    dfs.append(temp_df)
    time.sleep(random.uniform(2,5))
final=pd.concat(dfs,ignore_index=True)
final

page 1 : 200
Page: 1 - 20 companies
page 2 : 200
Page: 2 - 20 companies
page 3 : 200
Page: 3 - 20 companies
page 4 : 200
Page: 4 - 20 companies
page 5 : 200
Page: 5 - 20 companies
page 6 : 200
Page: 6 - 20 companies
page 7 : 200
Page: 7 - 20 companies
page 8 : 200
Page: 8 - 20 companies
page 9 : 200
Page: 9 - 20 companies
page 10 : 200
Page: 10 - 20 companies
page 11 : 200
Page: 11 - 20 companies
page 12 : 200
Page: 12 - 20 companies
page 13 : 200
Page: 13 - 20 companies
page 14 : 200
Page: 14 - 20 companies
page 15 : 200
Page: 15 - 20 companies
page 16 : 200
Page: 16 - 20 companies
page 17 : 200
Page: 17 - 20 companies
page 18 : 200
Page: 18 - 20 companies
page 19 : 200
Page: 19 - 20 companies
page 20 : 200
Page: 20 - 20 companies
page 21 : 200
Page: 21 - 20 companies
page 22 : 200
Page: 22 - 20 companies
page 23 : 200
Page: 23 - 20 companies
page 24 : 200
Page: 24 - 20 companies
page 25 : 200
Page: 25 - 20 companies
page 26 : 200
Page: 26 - 20 companies
page 27 : 200
Page: 27 - 20 companies
page 28 : 200
Page: 28 - 20 companies
page 29 : 200
Page: 29 - 20 companies
page 30 : 200
Page: 30 - 20 companies
page 31 : 200
Page: 31 - 20 companies
page 32 : 200
Page: 32 - 20 companies
page 33 : 200
Page: 33 - 20 companies
page 34 : 200
Page: 34 - 20 companies
page 35 : 200
Page: 35 - 20 companies
page 36 : 200
Page: 36 - 20 companies
page 37 : 200
Page: 37 - 20 companies
page 38 : 200
Page: 38 - 20 companies
page 39 : 200
Page: 39 - 20 companies
page 40 : 200
Page: 40 - 20 companies
page 41 : 200
Page: 41 - 20 companies
page 42 : 200
Page: 42 - 20 companies
page 43 : 200
Page: 43 - 20 companies
page 44 : 200
Page: 44 - 20 companies
page 45 : 200
Page: 45 - 20 companies
page 46 : 200
Page: 46 - 20 companies
page 47 : 200
Page: 47 - 20 companies
page 48 : 200
Page: 48 - 20 companies
page 49 : 200
Page: 49 - 20 companies
page 50 : 200
Page: 50 - 20 companies
page 51 : 200
Page: 51 - 20 companies
page 52 : 200
Page: 52 - 20 companies
page 53 : 200
Page: 53 - 20 companies
page 54 : 200
Page: 54 - 20 companies
page 55 : 200
Page: 55 - 20 companies
page 56 : 200
Page: 56 - 20 companies
page 57 : 200
Page: 57 - 20 companies
page 58 : 200
Page: 58 - 20 companies
page 59 : 200
Page: 59 - 20 companies
page 60 : 200
Page: 60 - 20 companies
page 61 : 200
Page: 61 - 20 companies
page 62 : 200
Page: 62 - 20 companies
page 63 : 200
Page: 63 - 20 companies
page 64 : 200
Page: 64 - 20 companies
page 65 : 200
Page: 65 - 20 companies
page 66 : 200
Page: 66 - 20 companies
page 67 : 200
Page: 67 - 20 companies
page 68 : 200
Page: 68 - 20 companies
page 69 : 200
Page: 69 - 20 companies
page 70 : 200
Page: 70 - 20 companies
page 71 : 200
Page: 71 - 20 companies
page 72 : 200
Page: 72 - 20 companies
page 73 : 200
Page: 73 - 20 companies
page 74 : 200
Page: 74 - 20 companies
page 75 : 200
Page: 75 - 20 companies
page 76 : 200
Page: 76 - 20 companies
page 77 : 200
Page: 77 - 20 companies
page 78 : 200
Page: 78 - 20 companies
page 79 : 200
Page: 79 - 20 companies
page 80 : 200
Page: 80 - 20 companies
page 81 : 200
Page: 81 - 20 companies
page 82 : 200
Page: 82 - 20 companies
page 83 : 200
Page: 83 - 20 companies
page 84 : 200
Page: 84 - 20 companies
page 85 : 200
Page: 85 - 20 companies
page 86 : 200
Page: 86 - 20 companies
page 87 : 200
Page: 87 - 20 companies
page 88 : 200
Page: 88 - 20 companies
page 89 : 200
Page: 89 - 20 companies
page 90 : 200
Page: 90 - 20 companies
page 91 : 200
Page: 91 - 20 companies
page 92 : 200
Page: 92 - 20 companies
page 93 : 200
Page: 93 - 20 companies
page 94 : 200
Page: 94 - 20 companies
page 95 : 200
Page: 95 - 20 companies
page 96 : 200
Page: 96 - 20 companies
page 97 : 200
Page: 97 - 20 companies
page 98 : 200
Page: 98 - 20 companies
page 99 : 200
Page: 99 - 20 companies
page 100 : 200
Page: 100 - 20 companies
page 101 : 200
Page: 101 - 20 companies
page 102 : 200
Page: 102 - 20 companies
page 103 : 200
Page: 103 - 20 companies
page 104 : 200
Page: 104 - 20 companies
page 105 : 200
Page: 105 - 20 companies
page 106 : 200
Page: 106 - 20 companies
page 107 : 200
Page: 107 - 20 companies
page 108 : 200
Page: 108 - 20 companies
page 109 : 200
Page: 109 - 20 companies
page 110 : 200
Page: 110 - 20 companies
page 111 : 200
Page: 111 - 20 companies
page 112 : 200
Page: 112 - 20 companies
page 113 : 200
Page: 113 - 20 companies
page 114 : 200
Page: 114 - 20 companies
page 115 : 200
Page: 115 - 20 companies
page 116 : 200
Page: 116 - 20 companies
page 117 : 200
Page: 117 - 20 companies
page 118 : 200
Page: 118 - 20 companies
page 119 : 200
Page: 119 - 20 companies
page 120 : 200
Page: 120 - 20 companies
page 121 : 200
Page: 121 - 20 companies
page 122 : 200
Page: 122 - 20 companies
page 123 : 200
Page: 123 - 20 companies
page 124 : 200
Page: 124 - 20 companies
page 125 : 200
Page: 125 - 20 companies
page 126 : 200
Page: 126 - 20 companies
page 127 : 200
Page: 127 - 20 companies
page 128 : 200
Page: 128 - 20 companies
page 129 : 200
Page: 129 - 20 companies
page 130 : 200
Page: 130 - 20 companies
page 131 : 200
Page: 131 - 20 companies
page 132 : 200
Page: 132 - 20 companies
page 133 : 200
Page: 133 - 20 companies
page 134 : 200
Page: 134 - 20 companies
page 135 : 200
Page: 135 - 20 companies
page 136 : 200
Page: 136 - 20 companies
page 137 : 200
Page: 137 - 20 companies
page 138 : 200
Page: 138 - 20 companies
page 139 : 200
Page: 139 - 20 companies
page 140 : 200
Page: 140 - 20 companies
page 141 : 200
Page: 141 - 20 companies
page 142 : 200
Page: 142 - 20 companies
page 143 : 200
Page: 143 - 20 companies
page 144 : 200
Page: 144 - 20 companies
page 145 : 200
Page: 145 - 20 companies
page 146 : 200
Page: 146 - 20 companies
page 147 : 200
Page: 147 - 20 companies
page 148 : 200
Page: 148 - 20 companies
page 149 : 200
Page: 149 - 20 companies
page 150 : 200
Page: 150 - 20 companies
page 151 : 200
Page: 151 - 20 companies
page 152 : 200
Page: 152 - 20 companies
page 153 : 200
Page: 153 - 20 companies
page 154 : 200
Page: 154 - 20 companies
page 155 : 200
Page: 155 - 20 companies
page 156 : 200
Page: 156 - 20 companies
page 157 : 200
Page: 157 - 20 companies
page 158 : 200
Page: 158 - 20 companies
page 159 : 200
Page: 159 - 20 companies
page 160 : 200
Page: 160 - 20 companies
page 161 : 200
Page: 161 - 20 companies
page 162 : 200
Page: 162 - 20 companies
page 163 : 200
Page: 163 - 20 companies
page 164 : 200
Page: 164 - 20 companies
page 165 : 200
Page: 165 - 20 companies
page 166 : 200
Page: 166 - 20 companies
page 167 : 200
Page: 167 - 20 companies
page 168 : 200
Page: 168 - 20 companies
page 169 : 200
Page: 169 - 20 companies
page 170 : 200
Page: 170 - 20 companies
page 171 : 200
Page: 171 - 20 companies
page 172 : 200
Page: 172 - 20 companies
page 173 : 200
Page: 173 - 20 companies
page 174 : 200
Page: 174 - 20 companies
page 175 : 200
Page: 175 - 20 companies
page 176 : 200
Page: 176 - 20 companies
page 177 : 200
Page: 177 - 20 companies
page 178 : 200
Page: 178 - 20 companies
page 179 : 200
Page: 179 - 20 companies
page 180 : 200
Page: 180 - 20 companies
page 181 : 200
Page: 181 - 20 companies
page 182 : 200
Page: 182 - 20 companies
page 183 : 200
Page: 183 - 20 companies
page 184 : 200
Page: 184 - 20 companies
page 185 : 200
Page: 185 - 20 companies
page 186 : 200
Page: 186 - 20 companies
page 187 : 200
Page: 187 - 20 companies
page 188 : 200
Page: 188 - 20 companies
page 189 : 200
Page: 189 - 20 companies
page 190 : 200
Page: 190 - 20 companies
page 191 : 200
Page: 191 - 20 companies
page 192 : 200
Page: 192 - 20 companies
page 193 : 200
Page: 193 - 20 companies
page 194 : 200
Page: 194 - 20 companies
page 195 : 200
Page: 195 - 20 companies
page 196 : 200
Page: 196 - 20 companies
page 197 : 200
Page: 197 - 20 companies
page 198 : 200
Page: 198 - 20 companies
page 199 : 200
Page: 199 - 20 companies
page 200 : 200
Page: 200 - 20 companies
page 201 : 200
Page: 201 - 20 companies
page 202 : 200
Page: 202 - 20 companies
page 203 : 200
Page: 203 - 20 companies
page 204 : 200
Page: 204 - 20 companies
page 205 : 200
Page: 205 - 20 companies
page 206 : 200
Page: 206 - 20 companies
page 207 : 200
Page: 207 - 20 companies
page 208 : 200
Page: 208 - 20 companies
page 209 : 200
Page: 209 - 20 companies
page 210 : 200
Page: 210 - 20 companies
page 211 : 200
Page: 211 - 20 companies
page 212 : 200
Page: 212 - 20 companies
page 213 : 200
Page: 213 - 20 companies
page 214 : 200
Page: 214 - 20 companies
page 215 : 200
Page: 215 - 20 companies
page 216 : 200
Page: 216 - 20 companies
page 217 : 200
Page: 217 - 20 companies
page 218 : 200
Page: 218 - 20 companies
page 219 : 200
Page: 219 - 20 companies
page 220 : 200
Page: 220 - 20 companies
page 221 : 200
Page: 221 - 20 companies
page 222 : 200
Page: 222 - 20 companies
page 223 : 200
Page: 223 - 20 companies
page 224 : 200
Page: 224 - 20 companies
page 225 : 200
Page: 225 - 20 companies
page 226 : 200
Page: 226 - 20 companies
page 227 : 200
Page: 227 - 20 companies
page 228 : 200
Page: 228 - 20 companies
page 229 : 200
Page: 229 - 20 companies
page 230 : 200
Page: 230 - 20 companies
page 231 : 200
Page: 231 - 20 companies
page 232 : 200
Page: 232 - 20 companies
page 233 : 200
Page: 233 - 20 companies
page 234 : 200
Page: 234 - 20 companies
page 235 : 200
Page: 235 - 20 companies
page 236 : 200
Page: 236 - 20 companies
page 237 : 200
Page: 237 - 20 companies
page 238 : 200
Page: 238 - 20 companies
page 239 : 200
Page: 239 - 20 companies
page 240 : 200
Page: 240 - 20 companies
page 241 : 200
Page: 241 - 20 companies
page 242 : 200
Page: 242 - 20 companies
page 243 : 200
Page: 243 - 20 companies
page 244 : 200
Page: 244 - 20 companies
page 245 : 200
Page: 245 - 20 companies
page 246 : 200
Page: 246 - 20 companies
page 247 : 200
Page: 247 - 20 companies
page 248 : 200
Page: 248 - 20 companies
page 249 : 200
Page: 249 - 20 companies
page 250 : 200
Page: 250 - 20 companies
page 251 : 200
Page: 251 - 20 companies
page 252 : 200
Page: 252 - 20 companies
page 253 : 200
Page: 253 - 20 companies
page 254 : 200
Page: 254 - 20 companies
page 255 : 200
Page: 255 - 20 companies
page 256 : 200
Page: 256 - 20 companies
page 257 : 200
Page: 257 - 20 companies
page 258 : 200
Page: 258 - 20 companies
page 259 : 200
Page: 259 - 20 companies
page 260 : 200
Page: 260 - 20 companies
page 261 : 200
Page: 261 - 20 companies
page 262 : 200
Page: 262 - 20 companies
page 263 : 200
Page: 263 - 20 companies
page 264 : 200
Page: 264 - 20 companies
page 265 : 200
Page: 265 - 20 companies
page 266 : 200
Page: 266 - 20 companies
page 267 : 200
Page: 267 - 20 companies
page 268 : 200
Page: 268 - 20 companies
page 269 : 200
Page: 269 - 20 companies
page 270 : 200
Page: 270 - 20 companies
page 271 : 200
Page: 271 - 20 companies
page 272 : 200
Page: 272 - 20 companies
page 273 : 200
Page: 273 - 20 companies
page 274 : 200
Page: 274 - 20 companies
page 275 : 200
Page: 275 - 20 companies
page 276 : 200
Page: 276 - 20 companies
page 277 : 200
Page: 277 - 20 companies
page 278 : 200
Page: 278 - 20 companies
page 279 : 200
Page: 279 - 20 companies
page 280 : 200
Page: 280 - 20 companies
page 281 : 200
Page: 281 - 20 companies
page 282 : 200
Page: 282 - 20 companies
page 283 : 200
Page: 283 - 20 companies
page 284 : 200
Page: 284 - 20 companies
page 285 : 200
Page: 285 - 20 companies
page 286 : 200
Page: 286 - 20 companies
page 287 : 200
Page: 287 - 20 companies
page 288 : 200
Page: 288 - 20 companies
page 289 : 200
Page: 289 - 20 companies
page 290 : 200
Page: 290 - 20 companies
page 291 : 200
Page: 291 - 20 companies
page 292 : 200
Page: 292 - 20 companies
page 293 : 200
Page: 293 - 20 companies
page 294 : 200
Page: 294 - 20 companies
page 295 : 200
Page: 295 - 20 companies
page 296 : 200
Page: 296 - 20 companies
page 297 : 200
Page: 297 - 20 companies
page 298 : 200
Page: 298 - 20 companies
page 299 : 200
Page: 299 - 20 companies
page 300 : 200
Page: 300 - 20 companies
page 301 : 200
Page: 301 - 20 companies
page 302 : 200
Page: 302 - 20 companies
page 303 : 200
Page: 303 - 20 companies
page 304 : 200
Page: 304 - 20 companies
page 305 : 200
Page: 305 - 20 companies
page 306 : 200
Page: 306 - 20 companies
page 307 : 200
Page: 307 - 20 companies
page 308 : 200
Page: 308 - 20 companies
page 309 : 200
Page: 309 - 20 companies
page 310 : 200
Page: 310 - 20 companies
page 311 : 200
Page: 311 - 20 companies
page 312 : 200
Page: 312 - 20 companies
page 313 : 200
Page: 313 - 20 companies
page 314 : 200
Page: 314 - 20 companies
page 315 : 200
Page: 315 - 20 companies
page 316 : 200
Page: 316 - 20 companies
page 317 : 200
Page: 317 - 20 companies
page 318 : 200
Page: 318 - 20 companies
page 319 : 200
Page: 319 - 20 companies
page 320 : 200
Page: 320 - 20 companies
page 321 : 200
Page: 321 - 20 companies
page 322 : 200
Page: 322 - 20 companies
page 323 : 200
Page: 323 - 20 companies
page 324 : 200
Page: 324 - 20 companies
page 325 : 200
Page: 325 - 20 companies
page 326 : 200
Page: 326 - 20 companies
page 327 : 200
Page: 327 - 20 companies
page 328 : 200
Page: 328 - 20 companies
page 329 : 200
Page: 329 - 20 companies
page 330 : 200
Page: 330 - 20 companies
page 331 : 200
Page: 331 - 20 companies
page 332 : 200
Page: 332 - 20 companies
page 333 : 200
Page: 333 - 20 companies
page 334 : 200
Page: 334 - 20 companies
page 335 : 200
Page: 335 - 20 companies
page 336 : 200
Page: 336 - 20 companies
page 337 : 200
Page: 337 - 20 companies
page 338 : 200
Page: 338 - 20 companies
page 339 : 200
Page: 339 - 20 companies
page 340 : 200
Page: 340 - 20 companies
page 341 : 200
Page: 341 - 20 companies
page 342 : 200
Page: 342 - 20 companies
page 343 : 200
Page: 343 - 20 companies
page 344 : 200
Page: 344 - 20 companies
page 345 : 200
Page: 345 - 20 companies
page 346 : 200
Page: 346 - 20 companies
page 347 : 200
Page: 347 - 20 companies
page 348 : 200
Page: 348 - 20 companies
page 349 : 200
Page: 349 - 20 companies
page 350 : 200
Page: 350 - 20 companies
page 351 : 200
Page: 351 - 20 companies
page 352 : 200
Page: 352 - 20 companies
page 353 : 200
Page: 353 - 20 companies
page 354 : 200
Page: 354 - 20 companies
page 355 : 200
Page: 355 - 20 companies
page 356 : 200
Page: 356 - 20 companies
page 357 : 200
Page: 357 - 20 companies
page 358 : 200
Page: 358 - 20 companies
page 359 : 200
Page: 359 - 20 companies
page 360 : 200
Page: 360 - 20 companies
page 361 : 200
Page: 361 - 20 companies
page 362 : 200
Page: 362 - 20 companies
page 363 : 200
Page: 363 - 20 companies
page 364 : 200
Page: 364 - 20 companies
page 365 : 200
Page: 365 - 20 companies
page 366 : 200
Page: 366 - 20 companies
page 367 : 200
Page: 367 - 20 companies
page 368 : 200
Page: 368 - 20 companies
page 369 : 200
Page: 369 - 20 companies
page 370 : 200
Page: 370 - 20 companies
page 371 : 200
Page: 371 - 20 companies
page 372 : 200
Page: 372 - 20 companies
page 373 : 200
Page: 373 - 20 companies
page 374 : 200
Page: 374 - 20 companies
page 375 : 200
Page: 375 - 20 companies
page 376 : 200
Page: 376 - 20 companies
page 377 : 200
Page: 377 - 20 companies
page 378 : 200
Page: 378 - 20 companies
page 379 : 200
Page: 379 - 20 companies
page 380 : 200
Page: 380 - 20 companies
page 381 : 200
Page: 381 - 20 companies
page 382 : 200
Page: 382 - 20 companies
page 383 : 200
Page: 383 - 20 companies
page 384 : 200
Page: 384 - 20 companies
page 385 : 200
Page: 385 - 20 companies
page 386 : 200
Page: 386 - 20 companies
page 387 : 200
Page: 387 - 20 companies
page 388 : 200
Page: 388 - 20 companies
page 389 : 200
Page: 389 - 20 companies
page 390 : 200
Page: 390 - 20 companies
page 391 : 200
Page: 391 - 20 companies
page 392 : 200
Page: 392 - 20 companies
page 393 : 200
Page: 393 - 20 companies
page 394 : 200
Page: 394 - 20 companies
page 395 : 200
Page: 395 - 20 companies
page 396 : 200
Page: 396 - 20 companies
page 397 : 200
Page: 397 - 20 companies
page 398 : 200
Page: 398 - 20 companies
page 399 : 200
Page: 399 - 20 companies
page 400 : 200
Page: 400 - 20 companies
page 401 : 200
Page: 401 - 20 companies
page 402 : 200
Page: 402 - 20 companies
page 403 : 200
Page: 403 - 20 companies
page 404 : 200
Page: 404 - 20 companies
page 405 : 200
Page: 405 - 20 companies
page 406 : 200
Page: 406 - 20 companies
page 407 : 200
Page: 407 - 20 companies
page 408 : 200
Page: 408 - 20 companies
page 409 : 200
Page: 409 - 20 companies
page 410 : 200
Page: 410 - 20 companies
page 411 : 200
Page: 411 - 20 companies
page 412 : 200
Page: 412 - 20 companies
page 413 : 200
Page: 413 - 20 companies
page 414 : 200
Page: 414 - 20 companies
page 415 : 200
Page: 415 - 20 companies
page 416 : 200
Page: 416 - 20 companies
page 417 : 200
Page: 417 - 20 companies
page 418 : 200
Page: 418 - 20 companies
page 419 : 200
Page: 419 - 20 companies
page 420 : 200
Page: 420 - 20 companies
page 421 : 200
Page: 421 - 20 companies
page 422 : 200
Page: 422 - 20 companies
page 423 : 200
Page: 423 - 20 companies
page 424 : 200
Page: 424 - 20 companies
page 425 : 200
Page: 425 - 20 companies
page 426 : 200
Page: 426 - 20 companies
page 427 : 200
Page: 427 - 20 companies
page 428 : 200
Page: 428 - 20 companies
page 429 : 200
Page: 429 - 20 companies
page 430 : 200
Page: 430 - 20 companies
page 431 : 200
Page: 431 - 20 companies
page 432 : 200
Page: 432 - 20 companies
page 433 : 200
Page: 433 - 20 companies
page 434 : 200
Page: 434 - 20 companies
page 435 : 200
Page: 435 - 20 companies
page 436 : 200
Page: 436 - 20 companies
page 437 : 200
Page: 437 - 20 companies
page 438 : 200
Page: 438 - 20 companies
page 439 : 200
Page: 439 - 20 companies
page 440 : 200
Page: 440 - 20 companies
page 441 : 200
Page: 441 - 20 companies
page 442 : 200
Page: 442 - 20 companies
page 443 : 200
Page: 443 - 20 companies
page 444 : 200
Page: 444 - 20 companies
page 445 : 200
Page: 445 - 20 companies
page 446 : 200
Page: 446 - 20 companies
page 447 : 200
Page: 447 - 20 companies
page 448 : 200
Page: 448 - 20 companies
page 449 : 200
Page: 449 - 20 companies
page 450 : 200
Page: 450 - 20 companies
page 451 : 200
Page: 451 - 20 companies
page 452 : 200
Page: 452 - 20 companies
page 453 : 200
Page: 453 - 20 companies
page 454 : 200
Page: 454 - 20 companies
page 455 : 200
Page: 455 - 20 companies
page 456 : 200
Page: 456 - 20 companies
page 457 : 200
Page: 457 - 20 companies
page 458 : 200
Page: 458 - 20 companies
page 459 : 200
Page: 459 - 20 companies
page 460 : 200
Page: 460 - 20 companies
page 461 : 200
Page: 461 - 20 companies
page 462 : 200
Page: 462 - 20 companies
page 463 : 200
Page: 463 - 20 companies
page 464 : 200
Page: 464 - 20 companies
page 465 : 200
Page: 465 - 20 companies
page 466 : 200
Page: 466 - 20 companies
page 467 : 200
Page: 467 - 20 companies
page 468 : 200
Page: 468 - 20 companies
page 469 : 200
Page: 469 - 20 companies
page 470 : 200
Page: 470 - 20 companies
page 471 : 200
Page: 471 - 20 companies
page 472 : 200
Page: 472 - 20 companies
page 473 : 200
Page: 473 - 20 companies
page 474 : 200
Page: 474 - 20 companies
page 475 : 200
Page: 475 - 20 companies
page 476 : 200
Page: 476 - 20 companies
page 477 : 200
Page: 477 - 20 companies
page 478 : 200
Page: 478 - 20 companies
page 479 : 200
Page: 479 - 20 companies
page 480 : 200
Page: 480 - 20 companies
page 481 : 200
Page: 481 - 20 companies
page 482 : 200
Page: 482 - 20 companies
page 483 : 200
Page: 483 - 20 companies
page 484 : 200
Page: 484 - 20 companies
page 485 : 200
Page: 485 - 20 companies
page 486 : 200
Page: 486 - 20 companies
page 487 : 200
Page: 487 - 20 companies
page 488 : 200
Page: 488 - 20 companies
page 489 : 200
Page: 489 - 20 companies
page 490 : 200
Page: 490 - 20 companies
page 491 : 200
Page: 491 - 20 companies
page 492 : 200
Page: 492 - 20 companies
page 493 : 200
Page: 493 - 20 companies
page 494 : 200
Page: 494 - 20 companies
page 495 : 200
Page: 495 - 20 companies
page 496 : 200
Page: 496 - 20 companies
page 497 : 200
Page: 497 - 20 companies
page 498 : 200
Page: 498 - 20 companies
page 499 : 200
Page: 499 - 20 companies

,name,ratings,count_of_rating,company_types,hq,salary,interview_counts,jobs,benefits
0,TCS,3.3,1.2L,IT Services & Consulting,Bengaluru,10.4L,11.4k,5.1k,10.9k
1,Accenture,3.7,75.6k,IT Services & Consulting,Bengaluru,7.2L,9.5k,19.7k,6.9k
2,Wipro,3.6,66.7k,IT Services & Consulting,Hyderabad,4.9L,7k,182,4.9k
3,Cognizant,3.7,63k,IT Services & Consulting,Hyderabad,6.1L,6.6k,906,5.6k
4,Capgemini,3.6,55.1k,IT Services & Consulting,Bengaluru,5L,5.7k,2.1k,3.8k
...,...,...,...,...,...,...,...,...,...
9975,Rayat Bahra University,4.5,115,Education & Training,Chandigarh,166,8,--,11
9976,Delta Exchange,4.8,115,Financial Services,Bengaluru,202,37,3,1
9977,East West Seeds,4.4,115,FMCG,Chhatrapati Sambhajinagar,394,10,--,11
9978,SPS Construction & Engineering Works,3.3,115,Engineering & Construction,Chennai,544,6,--,8
9979,Hatch Associates India,3.9,115,Electronics Manufacturing,Gurugram,611,12,--,7

In [9]:
final.to_csv('Ambitionbox_Companies_Raw.csv',index=False)

In [17]:
# Understanding The Data

In [10]:
final.sample(5)

,name,ratings,count_of_rating,company_types,hq,salary,interview_counts,jobs,benefits
663,Wockhardt,3.8,1.6k,Pharma,Chhatrapati Sambhajinagar,4.2k,67,29,183
7385,CLIRNet,3.6,158,Internet,Kolkata,509,14,24,6
732,Hyatt Regency,4.0,1.5k,Hospitality,New Delhi,3.1k,64,1,198
8155,Dinesh Engineers,3.9,142,Telecom,Mumbai,501,12,1,8
1397,Alivus Life Sciences,3.8,792,Pharma,Ankleshwar,4.1k,42,--,46

In [11]:
final.shape

(9980, 9)

In [12]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9980 non-null   object
 1   ratings           9971 non-null   object
 2   count_of_rating   9971 non-null   object
 3   company_types     9696 non-null   object
 4   hq                9980 non-null   object
 5   salary            9980 non-null   object
 6   interview_counts  9980 non-null   object
 7   jobs              9980 non-null   object
 8   benefits          9980 non-null   object
dtypes: object(9)
memory usage: 701.8+ KB

In [13]:
final.describe()

,name,ratings,count_of_rating,company_types,hq,salary,interview_counts,jobs,benefits
count,9980,9971,9971,9696,9980,9980,9980,9980,9980
unique,9559,38,945,83,257,1232,470,319,456
top,Gammastack,3.9,1.1k,IT Services & Consulting,Mumbai,1.1k,7,--,12
freq,2,1030,96,1312,1537,401,382,3586,367

In [22]:
# Checking & Removing Dulpicates

In [14]:
final[final.duplicated()]

,name,ratings,count_of_rating,company_types,hq,salary,interview_counts,jobs,benefits
180,State Street Corporation,3.5,4.3k,Financial Services,Bengaluru,35k,305,10,274
320,SRF,4.1,2.9k,Chemicals,Bharuch,9.4k,215,19,260
680,GE VERNOVA,4.1,1.6k,Power,Bengaluru,5.8k,115,6,14
860,Prodapt,3.5,1.3k,IT Services & Consulting,Chennai,10k,120,93,77
1320,Y-Axis Overseas Careers,4.1,839,Other,Hyderabad,1.5k,158,3,241
...,...,...,...,...,...,...,...,...,...
9965,Teqfocus Consulting,3.8,115,IT Services & Consulting,Bengaluru,677,11,4,1
9966,Arora Iron & Steel Rolling Mills,3.8,115,Iron & Steel,Ludhiana,481,7,--,5
9967,Brennan,3.7,115,IT Services & Consulting,Mumbai,545,3,6,7
9968,ekincare,3.0,115,Healthcare,Hyderabad,617,12,1,7
9970,Bop Realty,4.5,115,Real Estate,Noida,308,8,4,3

In [15]:
final=final.drop_duplicates().reset_index(drop=True)

In [16]:
final[final.duplicated()]

Empty DataFrame
Columns: [name, ratings, count_of_rating, company_types, hq, salary, interview_counts, jobs, benefits]
Index: []

In [26]:
# Checking Null Values

In [17]:
final.isnull().sum()

name                  0
ratings               9
count_of_rating       9
company_types       268
hq                    0
salary                0
interview_counts      0
jobs                  0
benefits              0
dtype: int64

In [ ]:
# Formatting the data

In [18]:
def convert_k(x):
    if pd.isna(x):
        return np.nan
    x=str(x).lower().replace(',','')
    if x.endswith('k'):
        return float(str(x).replace('k',''))*1000
    elif x.endswith('l'):
        return float(str(x).replace('l',''))*100000
    elif x=='--':
        return np.nan
        
    return float(x)

cols=['ratings','count_of_rating','salary','interview_counts','jobs','benefits']

for col in cols:
    final[col]=final[col].apply(convert_k)

In [28]:
# Replacing Null Values

In [19]:
for col in cols:
    
    final[col]=final[col].fillna(0)

In [20]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9563 entries, 0 to 9562
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9563 non-null   object
 1   ratings           9563 non-null   float64
 2   count_of_rating   9563 non-null   float64
 3   company_types     9295 non-null   object
 4   hq                9563 non-null   object
 5   salary            9563 non-null   float64
 6   interview_counts  9563 non-null   float64
 7   jobs              9563 non-null   float64
 8   benefits          9563 non-null   float64
dtypes: float64(6), object(3)
memory usage: 672.5+ KB

In [ ]:
# Checking null value after null handling

In [21]:
final.isnull().sum()

name                  0
ratings               0
count_of_rating       0
company_types       268
hq                    0
salary                0
interview_counts      0
jobs                  0
benefits              0
dtype: int64

In [23]:
final.loc[1]

name                               Accenture
ratings                                  3.7
count_of_rating                      75600.0
company_types       IT Services & Consulting
hq                                 Bengaluru
salary                              720000.0
interview_counts                      9500.0
jobs                                 19700.0
benefits                              6900.0
Name: 1, dtype: object

In [ ]:
# Final Clean Data before Analysis

In [24]:
final.to_csv('ambitionbox_companies_cleaned.csv',index=False)

In [ ]:
# checking where file is saved

In [25]:
import os
os.getcwd()

'C:\\Users\\soumy\\My Folder'