# Exploratory Data Analysis and Data Visualization

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Dataset Overview
### How many companies are present in the dataset?
### How many features (columns) are available?
### What are the data types of each feature?
### Are there any missing or duplicate values?
### Are the company names unique?

In [2]:
df= pd.read_csv('ambitionbox_companies_cleaned.csv')
df.head(5)

,name,ratings,count_of_rating,company_types,hq,salary,interview_counts,jobs,benefits
0,TCS,3.3,120000.0,IT Services & Consulting,Bengaluru,1040000.0,11400.0,5100.0,10900.0
1,Accenture,3.7,75600.0,IT Services & Consulting,Bengaluru,720000.0,9500.0,19700.0,6900.0
2,Wipro,3.6,66700.0,IT Services & Consulting,Hyderabad,490000.0,7000.0,182.0,4900.0
3,Cognizant,3.7,63000.0,IT Services & Consulting,Hyderabad,610000.0,6600.0,906.0,5600.0
4,Capgemini,3.6,55100.0,IT Services & Consulting,Bengaluru,500000.0,5700.0,2100.0,3800.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9563 entries, 0 to 9562
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9563 non-null   object
 1   ratings           9563 non-null   float64
 2   count_of_rating   9563 non-null   float64
 3   company_types     9295 non-null   object
 4   hq                9563 non-null   object
 5   salary            9563 non-null   float64
 6   interview_counts  9563 non-null   float64
 7   jobs              9563 non-null   float64
 8   benefits          9563 non-null   float64
dtypes: float64(6), object(3)
memory usage: 672.5+ KB

In [4]:
df.shape

(9563, 9)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

name                  0
ratings               0
count_of_rating       0
company_types       268
hq                    0
salary                0
interview_counts      0
jobs                  0
benefits              0
dtype: int64

In [7]:
df.nunique()

name                9559
ratings               39
count_of_rating      946
company_types         83
hq                   257
salary              1232
interview_counts     470
jobs                 319
benefits             456
dtype: int64

In [8]:
df.rename(columns={
    'name':'Name',
    'ratings':'Ratings',
    'count_of_rating':'Count_Of_Rating',
    'company_types':'Company_Types',
    'hq':'Hq',
    'salary':'Salary',
    'interview_counts':'Interview_Counts',
    'jobs':'Jobs',
    'benefits':'Benefits'
})

,Name,Ratings,Count_Of_Rating,Company_Types,Hq,Salary,Interview_Counts,Jobs,Benefits
0,TCS,3.3,120000.0,IT Services & Consulting,Bengaluru,1040000.0,11400.0,5100.0,10900.0
1,Accenture,3.7,75600.0,IT Services & Consulting,Bengaluru,720000.0,9500.0,19700.0,6900.0
2,Wipro,3.6,66700.0,IT Services & Consulting,Hyderabad,490000.0,7000.0,182.0,4900.0
3,Cognizant,3.7,63000.0,IT Services & Consulting,Hyderabad,610000.0,6600.0,906.0,5600.0
4,Capgemini,3.6,55100.0,IT Services & Consulting,Bengaluru,500000.0,5700.0,2100.0,3800.0
...,...,...,...,...,...,...,...,...,...
9558,Rayat Bahra University,4.5,115.0,Education & Training,Chandigarh,166.0,8.0,0.0,11.0
9559,Delta Exchange,4.8,115.0,Financial Services,Bengaluru,202.0,37.0,3.0,1.0
9560,East West Seeds,4.4,115.0,FMCG,Chhatrapati Sambhajinagar,394.0,10.0,0.0,11.0
9561,SPS Construction & Engineering Works,3.3,115.0,Engineering & Construction,Chennai,544.0,6.0,0.0,8.0
9562,Hatch Associates India,3.9,115.0,Electronics Manufacturing,Gurugram,611.0,12.0,0.0,7.0

In [9]:
df[df['Name'].duplicated(keep=False)]

KeyError: 'Name'

In [ ]:
df['Name'].duplicated().sum()

#### 58 Companies are being listed more than once.
#### Instead of deleting them lets create a combined list by doing arithmettic aggregation of multiple values.

In [ ]:
cs=df.groupby('Name').agg({
    'Ratings':'mean',
    'Count_Of_Rating':'mean',
    'Company_Types':'first',
    'Hq':'first',
    'Salary':'mean',
    'Interview_Counts':'mean',
    'Jobs':'mean',
    'Benefits':'mean'
}).reset_index()
cs.sort_values(by='Salary',ascending=False)

## Ratings Analysis
### What is the average company rating?
### Which companies have the highest and lowest ratings?
### How are ratings distributed?
### Are most companies rated above 4.0?

In [ ]:
avg_company_rating=cs['Ratings'].mean()
avg_company_rating

In [ ]:
cs.sort_values(by='Ratings',ascending=False).head(10)

In [ ]:
cs.sort_values(by='Ratings').head(10)

In [ ]:
rating=pd.cut(
    cs['Ratings'],
    bins=[0,1,2,3,4,5],
    labels=['0-1','1-2','2-3','3-4','4-5'],right=False
)
list=['0-1','1-2','2-3','3-4','4-5']
rating_count=rating.value_counts().reindex(list)
rating_count

In [ ]:
plt.figure(figsize=(12,6))
bars=plt.bar(rating_count.index,rating_count.values)
plt.xlabel('Rating')
plt.ylabel('Count')
plt.title('Count of Rating')
plt.grid(True,alpha=0.4)
plt.bar_label(bars,fmt='%d',padding=3)
plt.show()

#### Interpretation:
#### Average company rating is 3.18 among all compnay listed in ambition box.
#### Mostly companies are between 3-4 star(5991). Companies between 4-5 star is the second highest(2800).
#### Very few companies are there between 0-3 star. These companies with lower rating than three star should be avoided.

## Company Popularity

## Questions:

### Which companies have received the most ratings?
### Does a higher number of ratings indicate better ratings?
### Are highly rated companies also the most reviewed?

## Visualizations:

### Top 10 companies by rating count
### Scatter plot between Ratings and Count_Of_Rating

In [ ]:
top=cs.nlargest(10,'Count_Of_Rating')

In [ ]:
plt.figure(figsize=(12,6))
bars=plt.bar(top['Name'],top['Count_Of_Rating'],color='yellow',alpha=0.6)
plt.xlabel('Company_Name')
plt.ylabel('Count of Rating')
plt.grid(True,alpha=0.4)
plt.title('Companies with Highest Count of Reviews ')
plt.bar_label(bars,fmt='%d',padding=3)

In [ ]:
cs.nlargest(20,'Ratings')

In [ ]:
bottom=cs.nsmallest(10,'Count_Of_Rating')
bottom

In [ ]:
cs['Ratings'].corr(cs['Count_Of_Rating'])

In [ ]:
plt.figure(figsize=(12,6))
sns.scatterplot(x='Ratings',y='Count_Of_Rating',data=cs)
plt.xlabel('Ratings')
plt.ylabel('Count_Of_Rating')
plt.title('Rating vs Count_Of_Rating')
plt.grid(True,alpha=0.4)

### Interpretation: 
#### 1.TCS got most number of reviews.
#### 2. No, highest number of count of rating does not ensure highest rating, 
#### as I find very weak positive co relation among them .
#### 3. Most highly reviewed companies having lower count of ratings.

## Salary Analysis

### What is the average salary?
### Which companies offer the highest salaries?
### What is the salary distribution?
### Are higher-rated companies paying higher salaries?

## Visualizations:

#### Histogram
#### Boxplot
#### Scatter plot (Rating vs Salary)

In [ ]:
mean=cs['Salary'].mean()
print(f'Mean:{mean}')

In [ ]:
median=cs['Salary'].median()
print(f'Median:{median}')

In [ ]:
top_salary=cs.nlargest(10,'Salary')
top_salary

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(top_salary['Name'],top_salary['Salary'],color='red',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%d',padding=3)
plt.xlabel('Name of Company')
plt.ylabel('Salary')
plt.title('Top 10 Company Salary')

In [ ]:
cs['Salary'].skew()

In [ ]:
cs['Salary'].describe()

In [ ]:
# Salary Distribution
salary_count,bins=pd.qcut(
    cs['Salary'],
    5,
    labels=['Very Low','Low','Medium','High','Very High'],
    retbins=True
)
temp=pd.DataFrame({
    'Category':salary_count.cat.categories,
    'Range': [f'{bins[i]:.2f}-{bins[i+1]:.2f}' for i in range (len(bins)-1)],
    'Count': salary_count.value_counts().sort_index()
    
    
})


#temp.drop(columns={'Percentage'},axis=1)
y=temp['Count'].sum()

temp['Percentage']=[(j/y)*100 for j in temp['Count']]
temp

In [ ]:
plt.figure(figsize=(15,6))
plt.pie(temp['Count'],labels=temp['Range']+ temp['Category'],autopct='%1.1f%%')
plt.title('Distribution of salary based on almost equal distribution of Company in each bucket')

In [ ]:
# Salary Distribution
salary_count,bins=pd.cut(
    cs['Salary'],
    bins=5,
    labels=['Very Low','Low','Medium','High','Very High'],
    retbins=True
)
temp1=pd.DataFrame({
    'Category':salary_count.cat.categories,
    'Range': [f'{bins[i]:.2f}-{bins[i+1]:.2f}' for i in range (len(bins)-1)],
    'Count': salary_count.value_counts().sort_index(),
    'Description':['Bottom 20 Percentile ','20-40 Percentile','40-60 Percentile','60-80 Percentile','Top 20 Percentile ']

    
})
y=temp1['Count'].sum()

temp1['Percentage']=[(j/y)*100 for j in temp1['Count']]
temp1

In [ ]:
plt.figure(figsize=(15,6))
plt.pie(temp1['Count'],labels=temp1['Category'],autopct='%1.1f%%')
plt.title('Distribution of cpmapnies based on equal segmentation of salary gap')

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(temp['Category'],temp['Count'])
plt.bar_label(bar,fmt='%d',padding=3)
plt.xlabel('Category')
plt.ylabel('Count')
plt.title('Category vs Count')
plt.grid(True,alpha=0.4)

In [ ]:
salary=cs[cs['Salary']>0]
plt.figure(figsize=(12,6))
sns.boxplot(y=salary['Salary'])
plt.yscale('log')
plt.title('Salary Distribution Boxplot')
plt.grid(True,alpha=0.4)

## Scatter distribution between rating vs salary

In [ ]:
cs[['Salary','Ratings']].corr()

In [ ]:
plt.figure(figsize=(12,6))
sns.scatterplot(y=cs['Salary'],x=cs['Ratings'])
plt.title('Ratings vs Salary')

### Interpretation: 
#### 1.Salary is extremely right skewed(32.11).
#### 2. Median(966)) is more significant than Mean(3034)
#### 3. 99.9% of the company salary is upto 208000 per year which comes within very low range of salary
#### 3. in top twenty percentile of salary(2400-1040000) there is only 1819 companies which is 19.8% of the total company listed
#### 4. Rating has weak negative co relation with salary.
#### 5. Company giving highest salary is TCS

## Interview Analysis

### Which companies conduct the most interviews?
### Is there a relationship between salary and interview count?
### Do companies with more interviews also have more job openings?

## Visualizations:

#### Bar chart
#### Scatter plot

In [ ]:
top10=cs.nlargest(10,'Interview_Counts')
top10

In [ ]:
cs[['Salary','Interview_Counts']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Salary'],y=cs['Interview_Counts'],color='violet')
plt.xlabel('')
plt.ylabel('Interview Counts')
plt.grid(True,alpha=0.4)
plt.title('Salary vs Interview_Counts')

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(top10['Name'],top10['Interview_Counts'],color='Green',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.xlabel('Name')
plt.ylabel('Interview Counts')
plt.bar_label(bar,fmt='%d',padding=3)
plt.grid(True,alpha=0.4)
plt.title('Top 10 company based on Interview Counts')

##  Correlation = 0.94
### There is a strong positive relationship between salary and interview counts.
### Companies offering higher salaries generally receive more interview activity.

In [ ]:
cs[['Jobs','Interview_Counts']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Jobs'],y=cs['Interview_Counts'],color='red')
plt.xlabel('Jobs')
plt.ylabel('Interview Counts')
plt.grid(True,alpha=0.4)
plt.title('Jobs vs Interview_Counts')

## Correlation = 0.56
### There is a moderate positive relationship between job openings and interview counts.
### Companies with more job openings tend to conduct more interviews.

## Job Openings Analysis

### Which companies have the highest number of job openings?
### Are companies with more jobs also offering higher salaries?
### Do highly rated companies post more jobs?

In [ ]:
cs[cs['Jobs']==cs['Jobs'].max()]

In [ ]:
top_job=cs.nlargest(10,'Jobs').reset_index()
top_job

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(top_job['Name'],top_job['Jobs'],color='Green',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.xlabel('Company Name')
plt.ylabel('Job Openings')
plt.bar_label(bar,fmt='%d',padding=3)
plt.grid(True,alpha=0.4)
plt.title('Top 10 company based on Job Openings')

In [ ]:
cs[['Ratings','Jobs']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Ratings'],y=cs['Jobs'],color='red')
plt.ylabel('Jobs')
plt.xlabel('Ratings')
plt.grid(True,alpha=0.4)
plt.title('Jobs vs Ratings')

### Correlation = -0.009
### There is a very weak negative relationship or no relationship between job openings and Ratings.

In [ ]:
cs[['Salary','Jobs']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Jobs'],y=cs['Salary'],color='red')
plt.xlabel('Jobs')
plt.ylabel('Salary')
plt.grid(True,alpha=0.4)
plt.title('Salary vs Interview_Counts')

### Correlation = 0.59
#### There is a moderate positive relationship between job openings and Salary.
#### Companies with more job openings tend to offer higher salaries.

### Interpretation:
#### Accenture has most number of job openings
#### Companies with more job openings tend to offer higher salaries.
#### Companies with higher ratings does not ensure higher number of Job Openings.

## Benefits Analysis
### Which companies provide the highest number of employee benefits?
### Is there any relationship between benefits and company ratings?
### Do companies with better benefits attract more ratings?

In [ ]:
top_ben=cs.nlargest(10,'Benefits')
top_ben

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(top_ben['Name'],top_ben['Benefits'],color='Green',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.xlabel('Company Name')
plt.ylabel('benefits Offered')
plt.bar_label(bar,fmt='%d',padding=3)
plt.grid(True,alpha=0.4)
plt.title('Top 10 company based on Benefits Offered')

In [ ]:
cs[['Benefits','Ratings']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Ratings'],y=cs['Benefits'],color='red')
plt.xlabel('Ratings')
plt.ylabel('Benefits')
plt.grid(True,alpha=0.4)
plt.title('Ratings vs Benefits')

In [ ]:
# Correlation = 0.023
# There is a very weak positive relationship or no relationship between job openings and Ratings.

In [ ]:
cs[['Benefits','Salary','Jobs','Interview_Counts']].corr()

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Benefits'],y=cs['Salary'],color='blue')
plt.xlabel('Benefits')
plt.ylabel('Salary')
plt.grid(True,alpha=0.4)
plt.title('Salary vs Benefits')

###  Correlation = 0.92
### There is a strong positive relationship between salary and Benefits.
### Companies offering higher benefits generally Generally ofer more salary.

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Benefits'],y=cs['Jobs'],color='blue')
plt.xlabel('Benefits')
plt.ylabel('Jobs')
plt.grid(True,alpha=0.4)
plt.title('Jobs vs Benefits')

### Correlation = 0.51
### There is a moderate positive relationship between job openings and Benefits.
### Companies with more job openings tend to offer more Benefits.

In [ ]:
plt.figure(figsize=(12,6))
plt.scatter(x=cs['Benefits'],y=cs['Interview_Counts'],color='blue')
plt.xlabel('Benefits')
plt.ylabel('Interview_Counts')
plt.grid(True,alpha=0.4)
plt.title('Interview_Counts vs Benefits')

###  Correlation = 0.93
### There is a strong positive relationship between Interview counts and Benefits.
### Companies offering higher benefits generally conduct more interviews.

In [ ]:
###Interpretation:
#### TCS has most number of benefits
#### Companies with more benefits tend to offer higher salaries.
#### Companies with more benefits tend to offer More Jobs. 
#### Companies with more benefits tend to conduct more Interviews.
#### Companies with higher ratings does not ensure higher number of Benefits.

## Company Type Analysis

### Which company type is most common?
### Which company type has the highest average rating?
### Which company type offers the highest salaries?
### Which company type has the most job openings?

## Visualizations:

#### Countplot
#### Bar chart

In [ ]:
types=cs['Company_Types'].value_counts().head(50)
types

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(types.index,types.values,color='black',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%d',padding=3)
plt.xlabel('Name of Company Types')
plt.ylabel('Count')
plt.title(' Top 50 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

In [ ]:
plt.figure(figsize=(12,6))
plt.pie(types.values[:5],labels=types.index[:5],autopct='%1.1f%%')

In [ ]:
avg_rat=cs.groupby('Company_Types')['Ratings'].mean()
avg_rat_sorted=avg_rat.sort_values(ascending=False).head(20)
avg_rat_sorted

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(avg_rat_sorted.index,avg_rat_sorted.values,color='orange',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%f',padding=3)
plt.xlabel('Name of Company Types')
plt.ylabel('Avg. Rating')
plt.title(' Top 50 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

In [ ]:
avg_sal=cs.groupby('Company_Types')['Salary'].mean()
avg_sal_sorted=avg_sal.sort_values(ascending=False).head(20)
avg_sal_sorted

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(avg_sal_sorted.index,avg_sal_sorted.values,color='grey',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%d',padding=3)
plt.xlabel('Name of Company Types')
plt.ylabel('Avg. Salary')
plt.title(' Top 50 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

In [ ]:
count_Jobs=cs.groupby('Company_Types')['Jobs'].sum()
count_Jobs_sorted=count_Jobs.sort_values(ascending=False)
count_Jobs_sorted

### Interpretation
#### 1. Which company type is most common?
#### Ans- IT Services & Consulting (1199)
#### Which company type has the highest average rating?
#### Ans- Government (4.031373)
#### Which company type offers the highest salaries?
#### Ans- Average Highest Salary-Banking(13947.168675)
#### Which company type has the most job openings?
#### Ans- Total Job opening- IT Services & Consulting(74062.5)

## Headquarters Analysis

### Which cities have the highest number of companies?
### Which headquarters location has the highest average rating?
### Which location offers the highest salaries?
### Which location has the most job opportunities?

## Visualizations:

#### Top 10 headquarters
#### Bar chart

In [ ]:
top10=cs['Hq'].value_counts().head(10)
top10

In [ ]:
plt.figure(figsize=(12,6))
bar=sns.countplot(
    x=cs['Hq'],
    order=top10.index
)
plt.xticks(rotation=45,ha='right')
for container in bar.containers:
    plt.bar_label(container,fmt='%d',padding=3)
plt.ylabel('Count of Companies')

In [ ]:
plt.pie(top10.values,labels=top10.index,autopct='%1.1f%%')

In [ ]:
avg_rat=cs.groupby('Hq')['Ratings'].mean().sort_values(ascending=False).head(20)
avg_rat

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(avg_rat.index,avg_rat.values,color='grey',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%.2f',padding=3)
plt.xlabel('Name of HQ')
plt.ylabel('Avg. Ratings')
plt.title(' Top 20 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

In [ ]:
avg_sat=cs.groupby('Hq')['Salary'].mean().sort_values(ascending=False).head(20)
avg_sat

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(avg_sat.index,avg_sat.values,color='red',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%.2f',padding=3)
plt.xlabel('Name of HQ')
plt.ylabel('Avg. Salary')
plt.title(' Top 20 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

In [ ]:
avg_jobs=cs.groupby('Hq')['Jobs'].mean().sort_values(ascending=False).head(20)
avg_jobs

In [ ]:
plt.figure(figsize=(20,10))
bar=plt.bar(avg_jobs.index,avg_jobs.values,color='green',alpha=0.6)
plt.xticks(rotation=45,ha='right')
plt.bar_label(bar,fmt='%.2f',padding=3)
plt.xlabel('Name of HQ')
plt.ylabel('Avg. Jobs')
plt.title(' Top 20 Company Types and count of Enlisted Company')
plt.grid(True,alpha=0.6)

#### Which cities have the highest number of companies?
#### Ans- Mumbai(1426)
#### Which headquarters location has the highest average rating?
#### Ans-Tinsukia(4.8)
#### Which location offers the highest salaries?
#### Ans- jamnagar(12451.85)
#### Which location has the most job opportunities?
#### Ans- Nimbahera(65)

## Correlation Analysis

### Is salary positively correlated with ratings?
### Is interview count correlated with job openings?
### Are benefits related to salary?
### Which numerical variables are strongly correlated?

In [ ]:
corr=cs.corr(numeric_only=True)
corr

In [ ]:
plt.figure(figsize=(12,6))
sns.heatmap(corr,annot=True)

### Is salary positively correlated with ratings?
### Ans- Salary is having a very weak negative corelation(-0.017)
### Is interview count correlated with job openings?
### Ans- Interview Count is having moderate positive corelation with job openings(0.56)
### Are benefits related to salary?
### Ans- Benefits are strongly co related with salary(0.92)
### Which numerical variables are strongly correlated?
### Ans- 1. Benefits vs Count_of_rating(0.97)
###      2. Benefits vs Salary (0.92)
###      3. Benefits vs Interview_Counts(0.94)
###      4. Salary vs Interview_Counts(0.94)
###      5. Salary vs Count_of_Ratings(0.91)
###      6. Interview_Counts vs Count_of_Ratings(0.95)

## Outlier Detection

### Are there extreme salary values?
### Are there companies with unusually high ratings count?
### Are there companies with exceptionally high interview counts?

## Visualizations:

#### Boxplots

In [ ]:
sns.boxplot(y=cs['Salary'])
plt.yscale('log')

### Interpretation:
#### 1. Low median Value(966),high Mean value due to outliers
#### 2. outliers present above upper whiskers
#### 3. Right Skewed Data

In [ ]:
sns.boxplot(y=cs['Ratings'])

### Interpretation:
#### 1. high median Value(3.8),low Mean value due to lower bound outliers
#### 2. outliers present above mostly below lower whiskers
#### 3. slightly left Skewed Data
#### Most of the companies having good ratings with few exceptionally low rating.

In [ ]:
sns.boxplot(y=cs['Interview_Counts'])
plt.yscale('log')

### Interpretation:
#### 1. Low median Value(20),high Mean value due to outliers
#### 2. outliers present above upper whiskers
#### 3. highly Right Skewed Data
#### most companies have lower interview count, with few are having exceptionally high interview counts.

## Business Insights

### Which companies combine high salary + high rating?
### Which companies have many job openings but low ratings?
### Which companies are popular despite average salaries?
### Which companies provide good benefits with high ratings?
### Which companies appear to be the best employers overall?

In [ ]:
# Which companies combine high salary + high rating?

In [ ]:
cs[(cs['Salary']>=cs['Salary'].quantile(0.8))& (cs['Ratings']>=cs['Ratings'].quantile(0.8))].sort_values(by='Jobs',ascending=False).reset_index()

In [ ]:
# Which companies have many job openings but low ratings?

In [ ]:
cs[(cs['Jobs']>=cs['Jobs'].quantile(0.8))& (cs['Ratings']<=cs['Ratings'].quantile(0.2))].sort_values(by='Jobs',ascending=False).reset_index()

In [ ]:
# Which companies are popular despite average salaries?

In [ ]:
cs[(cs['Count_Of_Rating']>=cs['Count_Of_Rating'].quantile(0.8))& (cs['Salary']>=cs['Salary'].quantile(0.4))& (cs['Salary']<=cs['Salary'].quantile(0.8))].sort_values(by='Jobs',ascending=False).reset_index()

In [ ]:
# Which companies provide good benefits with high ratings?

In [ ]:
cs[(cs['Benefits']>=cs['Benefits'].quantile(0.8))& (cs['Ratings']>=cs['Ratings'].quantile(0.8))].sort_values(by='Ratings',ascending=False).reset_index()

In [ ]:
# Which companies appear to be the best employers overall?

In [ ]:
cs[(cs['Benefits']>=cs['Benefits'].quantile(0.8))& (cs['Ratings']>=cs['Ratings'].quantile(0.8)) & (cs['Salary']>=cs['Salary'].quantile(0.8)) & (cs['Count_Of_Rating']>=cs['Count_Of_Rating'].quantile(0.8)) & (cs['Jobs']>=cs['Jobs'].quantile(0.8)) & (cs['Interview_Counts']>=cs['Interview_Counts'].quantile(0.8))].sort_values(by='Salary',ascending=False).reset_index()

## Final Business Questions 
### What is the overall distribution of company ratings?
### Which companies are the highest and lowest rated?
### Which companies offer the highest salaries?
### Is there a relationship between ratings and salary?
### Which company types dominate the dataset?
### Which headquarters locations have the most companies?
### Which companies have the most job openings?
### Which companies conduct the most interviews?
### Do companies with more benefits receive better ratings?
### Which factors appear to influence company popularity the most?

In [ ]:
# What is the overall distribution of company ratings?

In [ ]:
ab=pd.cut(
    cs['Ratings'],
    bins=[0,1,2,3,4,5],
    labels=['0-1','1-2','2-3','3-4','4-5'],right=False
)
list=['0-1','1-2','2-3','3-4','4-5']
tp=ab.value_counts().reindex(list)
tp

In [ ]:
plt.figure(figsize=(12,6))
plt.pie(tp.values,labels=tp.index,autopct='%1.1f%%')

In [ ]:
plt.figure(figsize=(12,6))
bar=plt.bar(tp.index,tp.values)
plt.bar_label(bar,fmt='%d',padding=3)
plt.grid(True,alpha=0.6)
plt.xlabel('Rating Range')
plt.ylabel('Count')
plt.title('Distribution of Rating')

In [ ]:
order=['0-1','1-2','2-3','3-4','4-5']
sns.countplot(
    x=ab,
    order=order
    
)

In [ ]:
# top 10 percentile rated company

In [ ]:
cs[cs['Ratings']>=cs['Ratings'].quantile(0.95)]

In [ ]:
# last 10 percentile rated company

In [ ]:
cs[cs['Ratings']<=cs['Ratings'].quantile(0.05)]

In [ ]:
# which company pays highest salary

In [ ]:
cs[cs['Salary']>=cs['Salary'].quantile(0.95)].sort_values(by='Salary',ascending=False).reset_index()

In [ ]:
# Is there a relationship between ratings and salary?

In [ ]:
corr=cs[['Ratings','Salary']].corr()
corr

In [ ]:
# no any strong relationship observed. very weak negative co relation is there

In [ ]:
# Which company types dominate the dataset?
cs['Company_Types'].value_counts().head(20)

In [ ]:
# Ans- IT Services & Consulting

In [ ]:
# Which headquarters locations have the most companies?
cs['Hq'].value_counts().head(20)

In [ ]:
# Ans- Mumbai

In [ ]:
# Which companies have the most job openings?

cs[cs['Jobs']==cs['Jobs'].max()]

In [ ]:
# Ans- Accenture

In [ ]:
# Which companies conduct the most interviews?
cs[cs['Interview_Counts']==cs['Interview_Counts'].max()]

In [ ]:
# Ans- TCS

In [ ]:
# Do companies with more benefits receive better ratings?
cs[['Benefits','Ratings']].corr()

In [ ]:
# Ans- Benefit and rating have weak positive corelation.

In [ ]:
# Which factors appear to influence company popularity the most?

In [ ]:
cs.corr(numeric_only=True)['Count_Of_Rating']

In [ ]:
# Ans- Salary,Interview_Counts,Benefits - These 3 factors truely effect the popularity of company.
# Mild Contributor- Jobs

## Final Business Insights

• Most companies have ratings between 3 and 4.

• Salary distribution is highly right-skewed.

• TCS leads in reviews, interviews, and benefits.

• Salary is strongly associated with interview activity.

• Job openings show a moderate association with interview counts.

• IT Services & Consulting dominates the dataset.

• Major cities such as Bengaluru and Hyderabad host many leading companies.

• Several numerical variables contain outliers, suggesting caution when interpreting averages.